name: Movie Box Lint
on:
  pull_request:
    paths:
      - "movie-box/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: movie-box
    steps:
      - uses: actions/checkout@v4.2.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm i

      - name: Prettier
        run: npm run prettier:check

      - name: Lint
        run: npm run lint
