name: Movie Box Deploy
on:
  pull_request:
    paths:
      - "movie-box/**"
  push:
    branches: [ main ]
    paths:
      - "movie-box/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Build the project
        uses: docker/build-push-action@v4
        with:
          context: ./movie-box
          file: ./movie-box/Dockerfile
          load: true
          tags: movie-box:latest
          push: false

      - name: Extract build artifacts
        run: |
          docker create --name temp movie-box:latest
          docker cp temp:/app/dist ./dist
          docker rm temp

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "movie-box/dist/*"
          target: "/var/www/movie-box/html/"
          rm: true
